const provincelist = {
  '上海': 'shanghai',
  '天津': 'tianjin',
  '重庆': 'chongqing',
  '香港': 'xianggang',
  '澳门': 'aomen',
  '安徽': 'anhui',
  '福建': 'fujian',
  '广东': 'guangdong',
  '广西': 'guangxi',
  '贵州': 'guizhou',
  '甘肃': 'gansu',
  '海南': 'hainan',
  '河北': 'hebei',
  '河南': 'henan',
  '黑龙江': 'heilongjiang',
  '湖北': 'hubei',
  '湖南': 'hunan',
  '吉林': 'jilin',
  '江苏': 'jiangsu',
  '江西': 'jiangxi',
  '辽宁': 'liaoning',
  '内蒙古': 'neimenggu',
  '宁夏': 'ningxia',
  '青海': 'qinghai',
  '陕西': 'shanxi1',
  '山西': 'shanxi',
  '山东': 'shandong',
  '四川': 'sichuan',
  '台湾': 'taiwan',
  '西藏': 'xizang',
  '新疆': 'xinjiang',
  '云南': 'yunnan',
  '浙江': 'zhejiang',
  '北京': 'beijing'
}

export function convertCN2EN (cname) {
  return provincelist[cname]
}
